import { NumberInput } from "@angular/cdk/coercion";
import { Time } from "@angular/common";

 export interface Applicant {
    applicantID: number;
    profileID: number;
    profileType: string;
    firstName?: string;
    lastName?: string;
    fullName: string;
    fHAEmpNo: string;
    postingIDNum: number;
    postingIDSuffix: string;
    mapToPostingID: string;
    postingDate: Date;
    costCenter: string;
    postingManager: string;
    postingMngrADUsername: string;
    deptName: string;
    appliedDate: Date;
    approvalStatus: string;
    city: string;
    address1: string;
    province: string;
    country: string;
    phonePrimary: string;
    postalCode: string;
    email: string;
    interviewingManager: string;
    hiringFairDate: Date;
    interviewTime: Time;
    fairAlternative: string;
    onsiteDeadline: Date;
    hireStartDate: Date;
    fundingDate: Date;
    nurseType: number;
    programCompletionDate: Date;
    secondYrCompletiondate: Date;
    registration: string;
    eduVerificationComplete: boolean;
    schoolName: string;
    cPR_Expiry: Date;
    modifiedOn: Date;
    modifiedBy: string;
    site: string;    
    selected: boolean;
}
